# Shared network 'express-mongo-mysql' makes service 'mongo' & 'mysql' available to service 'express'. You can connect using the service name in MONGODB_URI like this: mongodb://[SERVICE_NAME]:27017/

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: '.env'
    depends_on:
      mongo:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - express-mongo-mysql
    expose:
      - 3000
    ports:
      - 3000:3000
    develop:
      watch:
        # TODO: Sync would be faster but harder to setup.
        # - action: sync
        #   path: ./src
        #   target: /usr/src/app/src
        #   ignore:
        #     - node_modules/
        - action: rebuild
          path: .
  mongo:
    image: mongo:7.0.11
    networks:
      - express-mongo-mysql
    expose:
      - 27017
  mysql:
    image: mariadb:lts
    environment:
      - MARIADB_DATABASE=serlo
      - MARIADB_USER=root
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=secret
    # https://mariadb.com/kb/en/using-healthcheck-sh/
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    # image: ghcr.io/serlo/serlo-mysql-database:latest
    # platform: linux/x86_64
    # pull_policy: always
    # ports:
    #   - '3306:3306'
    networks:
      - express-mongo-mysql
networks:
  express-mongo-mysql:
