services:
  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql