services:
  mongo:
    image: mongo:6
    expose:
      - 27017
    ports:
      - 27017:27017
  mariadb:
    image: mariadb:10 # Match major version on Uberspace
    environment:
      - MARIADB_DATABASE=serlo
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=secret
    # https://mariadb.com/kb/en/using-healthcheck-sh/
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - 3306
    ports:
      - 3306:3306
